/**
 * Warp terminal backend for pi-interactive-subagents.
 *
 * Warp is not a multiplexer and exposes no `send-keys` / `capture-pane` style
 * CLI, so this backend reaches class-1 parity through a **surface directory
 * handshake** instead of keystroke injection:
 *
 *   1. We allocate a surface directory and drop `.pi-warp-surface` + `surface.json`.
 *   2. We ask Warp to open a tab whose cwd IS that directory
 *      (`warp://action/new_tab?path=<surface dir>` — works on Linux, Windows and
 *      macOS, needs no Warp "Scripting" toggle).
 *   3. A tiny shell hook (installed once into bashrc/zshrc/fish/PowerShell
 *      profile — see `scripts/install-warp-hook.mjs`) notices the marker, and
 *      execs `pi-warp-bootstrap`, which becomes the pane driver:
 *        - runs the requested command under a pty (`script -qfe` on Unix),
 *        - mirrors everything to `out.log`  → gives us `readScreen`,
 *        - feeds `in.fifo` into the child's stdin → gives us `sendCommand` /
 *          `sendEscape`,
 *        - writes `__SUBAGENT_DONE_<code>__` + `status.json` on exit → gives us
 *          `pollForExit` crash detection with the existing sentinel contract.
 *
 * Optional niceties (rename/close/split/focus real Warp panes) go through
 * Warp's hidden local-control CLI `warpctrl` when the user has enabled
 * Settings > Scripting. `warpctrl` is *not* required, and is currently not
 * published on Windows, so every code path degrades gracefully.
 *
 * See docs/adr/0011-warp-terminal-class-1-backend.md.
 */
import { execFile, execFileSync, spawn } from "node:child_process";
import { promisify } from "node:util";
import {
  appendFileSync,
  closeSync,
  existsSync,
  fstatSync,
  mkdirSync,
  openSync,
  readFileSync,
  readSync,
  readdirSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { homedir, tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const execFileAsync = promisify(execFile);

/** Bumped when the on-disk surface handshake changes shape. */
export const WARP_SURFACE_PROTOCOL = 1;

const HERE = dirname(fileURLToPath(import.meta.url));

/** Files that make up one surface directory. */
export const SURFACE_FILES = {
  marker: ".pi-warp-surface",
  spec: "surface.json",
  env: "surface.env",
  status: "status.json",
  log: "out.log",
  input: process.platform === "win32" ? "in.cmd" : "in.fifo",
} as const;

/** POSIX single-quote escaping: the only safe way to hand data to a shell. */
export function shQuote(value: string): string {
  return `'${String(value).replace(/'/g, `'\\''`)}'`;
}

/** Render surface.json as a file the pane bootstrap can simply `.` (source). */
export function renderSurfaceEnv(spec: WarpSurfaceSpec): string {
  const lines = [
    "# generated by pi-interactive-subagents — do not edit",
    `PI_WARP_PROTOCOL=${shQuote(String(spec.protocol))}`,
    `PI_WARP_ID=${shQuote(spec.id)}`,
    `PI_WARP_NAME=${shQuote(spec.name)}`,
    `PI_WARP_CWD=${shQuote(spec.cwd)}`,
    `PI_WARP_COMMAND=${shQuote(spec.command ?? "")}`,
    `PI_WARP_LOG=${shQuote(spec.log)}`,
    `PI_WARP_INPUT=${shQuote(spec.input)}`,
    `PI_WARP_STATUS=${shQuote(spec.status)}`,
  ];
  for (const [key, value] of Object.entries(spec.env ?? {})) {
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue; // never emit a bogus name
    lines.push(`export ${key}=${shQuote(value)}`);
  }
  return lines.join("\n") + "\n";
}

export interface WarpSurfaceSpec {
  protocol: number;
  id: string;
  name: string;
  /** Directory the pane should `cd` into before running `command`. */
  cwd: string;
  /** Command executed by the bootstrap (a script path, usually). */
  command: string | null;
  /** Absolute paths, resolved for the pane's shell. */
  log: string;
  input: string;
  status: string;
  createdAt: number;
  /** Environment injected into the pane before `command` runs. */
  env: Record<string, string>;
}

export interface WarpSurfaceStatus {
  id: string;
  pid?: number;
  /** pid of the command running under the pty, when the bootstrap reports it. */
  childPid?: number;
  /** "starting" | "running" | "exited" */
  state: string;
  exitCode?: number;
  updatedAt?: number;
  /** Set when the exit was inferred from a dead pid rather than a clean trap. */
  stale?: boolean;
  /** Pane geometry reported by the bootstrap, used to render the transcript. */
  rows?: number;
  cols?: number;
  /** Sanitised tab title the bootstrap asserted (diagnostics; OSC output is not logged). */
  title?: string;
  /** Warp pane id, filled in by `warpctrl` when local control is available. */
  paneId?: string;
}

// ---------------------------------------------------------------------------
// Environment detection
// ---------------------------------------------------------------------------

function firstExisting(candidates: (string | undefined)[]): string | null {
  for (const c of candidates) {
    if (c && existsSync(c)) return c;
  }
  return null;
}

/** True when this pi process is itself running inside a Warp session. */
export function isInsideWarp(): boolean {
  return (
    process.env.TERM_PROGRAM === "WarpTerminal" ||
    process.env.WARP_TERMINAL_SESSION_UUID != null ||
    process.env.WARP_IS_LOCAL_SHELL_SESSION === "1"
  );
}

/** Warp per-channel data dir (`~/.warp`, `~/.warp-preview`, ...). */
export function warpDataDir(): string {
  const explicit = process.env.PI_WARP_DATA_DIR;
  if (explicit) return explicit;
  const home = homedir();
  const channels = [".warp", ".warp-preview", ".warp-dev", ".warp-oss"];
  for (const c of channels) {
    const p = join(home, c);
    if (existsSync(p)) return p;
  }
  return join(home, ".warp");
}

let resolvedWarpBin: string | null | undefined;
/** Executable used to hand `warp://` URLs to the running Warp app. */
export function getWarpBin(): string | null {
  if (resolvedWarpBin !== undefined) return resolvedWarpBin;
  if (process.env.PI_WARP_BIN) {
    resolvedWarpBin = process.env.PI_WARP_BIN;
    return resolvedWarpBin;
  }

  if (process.platform === "win32") {
    resolvedWarpBin = firstExisting([
      join(process.env.LOCALAPPDATA ?? "", "Programs", "Warp", "warp.exe"),
      join(process.env.LOCALAPPDATA ?? "", "Programs", "Warp", "Warp.exe"),
      join(process.env.ProgramFiles ?? "", "Warp", "warp.exe"),
    ]);
    return resolvedWarpBin;
  }

  if (process.platform === "darwin") {
    resolvedWarpBin = firstExisting(["/Applications/Warp.app/Contents/MacOS/stable"]);
    return resolvedWarpBin;
  }

  resolvedWarpBin = firstExisting([
    "/usr/bin/warp-terminal",
    "/opt/warpdotdev/warp-terminal/warp",
    "/usr/local/bin/warp-terminal",
    join(homedir(), ".local", "bin", "warp-terminal"),
  ]);
  return resolvedWarpBin;
}

let resolvedWarpctrl: string | null | undefined;
/**
 * Resolve Warp's local-control CLI, if the user installed/enabled it.
 * Not required by this backend — only used for cosmetic/pane-level actions.
 */
export function getWarpctrlBin(): string | null {
  if (resolvedWarpctrl !== undefined) return resolvedWarpctrl;
  if (process.env.PI_WARPCTRL_BIN) {
    resolvedWarpctrl = process.env.PI_WARPCTRL_BIN;
    return resolvedWarpctrl;
  }
  const names = ["warpctrl", "warpctrl-preview", "warpctrl-dev"];
  for (const name of names) {
    const candidate = firstExisting([
      `/usr/local/bin/${name}`,
      join(homedir(), ".local", "bin", name),
      join(process.env.LOCALAPPDATA ?? "", "Programs", "Warp", "bin", `${name}.exe`),
    ]);
    if (candidate) {
      resolvedWarpctrl = candidate;
      return resolvedWarpctrl;
    }
  }
  resolvedWarpctrl = null;
  return null;
}

/** True when `warpctrl` exists AND a same-channel instance answers. */
export function isWarpctrlAvailable(): boolean {
  const bin = getWarpctrlBin();
  if (!bin) return false;
  try {
    const out = execFileSync(bin, ["--output-format", "json", "instance", "list"], {
      encoding: "utf8",
      timeout: 4000,
      stdio: ["ignore", "pipe", "ignore"],
    });
    const parsed = JSON.parse(out);
    const instances = parsed?.instances ?? parsed?.data?.instances ?? [];
    return Array.isArray(instances) && instances.length > 0;
  } catch {
    return false;
  }
}

/** Root for surface directories and installer receipts. */
export function warpStateDir(): string {
  if (process.env.PI_WARP_STATE_DIR) return process.env.PI_WARP_STATE_DIR;
  if (process.platform === "win32") {
    return join(
      process.env.LOCALAPPDATA ?? join(homedir(), "AppData", "Local"),
      "pi-interactive-subagents",
      "warp",
    );
  }
  const xdg = process.env.XDG_STATE_HOME ?? join(homedir(), ".local", "state");
  return join(xdg, "pi-interactive-subagents", "warp");
}

export function hookReceiptPath(): string {
  return join(warpStateDir(), "hook-installed.json");
}

/**
 * The pane hook is what makes Warp scriptable for us. Without it a new Warp
 * tab is just an idle shell and nothing can be launched into it.
 */
export function isWarpHookInstalled(): boolean {
  if (process.env.PI_WARP_HOOK === "1") return true;
  return existsSync(hookReceiptPath());
}

/**
 * Warp counts as an available backend when:
 *  - pi is running inside Warp (or the user forced `PI_MUX_BACKEND=warp`),
 *  - we can hand URLs to the Warp app,
 *  - the pane bootstrap hook is installed.
 */
export function isWarpRuntimeAvailable(): boolean {
  if (!isInsideWarp() && process.env.PI_MUX_BACKEND?.toLowerCase() !== "warp") return false;
  if (!getWarpBin() && !canOpenUrlGenerically()) return false;
  return isWarpHookInstalled();
}

function canOpenUrlGenerically(): boolean {
  if (process.platform === "win32") return true; // `cmd /c start`
  if (process.platform === "darwin") return true; // `open`
  return existsSync("/usr/bin/xdg-open");
}

export function warpSetupHint(): string {
  const lines = [
    "Warp detected, but the pi pane hook is not installed yet.",
    "Run: node scripts/install-warp-hook.mjs --install",
    "(adds one guarded line to your shell profile; `--uninstall` reverts it).",
  ];
  if (process.platform === "win32") {
    lines.push("On Windows the hook is installed into your PowerShell $PROFILE.");
  }
  return lines.join(" ");
}

// ---------------------------------------------------------------------------
// Surface lifecycle
// ---------------------------------------------------------------------------

function surfacesRoot(): string {
  return join(warpStateDir(), "surfaces");
}

export function surfaceDir(id: string): string {
  return join(surfacesRoot(), id);
}

function newSurfaceId(): string {
  return `w${Date.now().toString(36)}${Math.random().toString(36).slice(2, 7)}`;
}

/** Bootstrap script shipped with the package, per pane shell family. */
export function bootstrapScriptPath(): string {
  const file = process.platform === "win32" ? "pi-warp-bootstrap.ps1" : "pi-warp-bootstrap.sh";
  return join(HERE, "warp-bootstrap", file);
}

export interface CreateWarpSurfaceOptions {
  /** Working directory the pane should land in. Defaults to process.cwd(). */
  cwd?: string;
  /** Command to execute in the pane. When omitted the pane opens an idle shell. */
  command?: string;
  /** Extra environment for the pane. */
  env?: Record<string, string>;
  /** `tab` (default) gives each subagent full width; `split` uses warpctrl. */
  mode?: "tab" | "split";
  /** Split direction, only meaningful with warpctrl available. */
  direction?: "left" | "right" | "up" | "down";
}

/**
 * Allocate a surface directory + ask Warp to open a tab on it.
 * Returns the surface id, which doubles as the pane handle used by every other
 * function in this module.
 */
export function createWarpSurface(name: string, options: CreateWarpSurfaceOptions = {}): string {
  const id = newSurfaceId();
  const dir = surfaceDir(id);
  mkdirSync(dir, { recursive: true });

  const spec: WarpSurfaceSpec = {
    protocol: WARP_SURFACE_PROTOCOL,
    id,
    name,
    cwd: options.cwd ?? process.cwd(),
    command: options.command ?? null,
    log: join(dir, SURFACE_FILES.log),
    input: join(dir, SURFACE_FILES.input),
    status: join(dir, SURFACE_FILES.status),
    createdAt: Date.now(),
    env: {
      PI_SUBAGENT_SURFACE: id,
      PI_SUBAGENT_SURFACE_DIR: dir,
      PI_WARP_SURFACE_NAME: name,
      ...(options.env ?? {}),
    },
  };

  writeFileSync(join(dir, SURFACE_FILES.spec), JSON.stringify(spec, null, 2));
  // Shell-sourceable twin of surface.json. The bootstrap used to parse JSON
  // with sed, which silently truncated any value containing a quote or
  // backslash — and those values are then executed. Quoting here, once, in a
  // language that knows the data, removes that whole class of bug.
  writeFileSync(join(dir, SURFACE_FILES.env), renderSurfaceEnv(spec));
  writeFileSync(join(dir, SURFACE_FILES.log), "");
  writeStatus(id, { id, state: "starting", updatedAt: Date.now() });
  // Marker last: the hook only fires once the spec is complete.
  writeFileSync(join(dir, SURFACE_FILES.marker), `${WARP_SURFACE_PROTOCOL}\n`);

  if (options.mode === "split" && isWarpctrlAvailable()) {
    // warpctrl splits the *active* pane and the new pane inherits the active
    // pane's cwd, so we cd via the hook marker copied into the split's cwd.
    warpctrl(["pane", "split", "--direction", options.direction ?? "right"]);
    // The split inherits our cwd; hand it the surface dir explicitly.
    openWarpTab(dir);
  } else {
    openWarpTab(dir);
  }

  if (isWarpctrlAvailable()) {
    try {
      warpctrl(["pane", "rename", name]);
    } catch {
      /* cosmetic */
    }
  }
  return id;
}

/** Ask the running Warp app to open a new tab rooted at `path`. */
export function openWarpTab(path: string): void {
  // Escape hatch for tests / dry-runs: prepare the surface but do not open UI.
  if (process.env.PI_WARP_NO_LAUNCH === "1") return;
  const url = `warp://action/new_tab?path=${encodeURIComponent(path)}`;
  const bin = getWarpBin();
  if (bin) {
    detach(bin, [url]);
    return;
  }
  if (process.platform === "win32") {
    detach("cmd", ["/c", "start", "", url]);
  } else if (process.platform === "darwin") {
    detach("open", [url]);
  } else {
    detach("xdg-open", [url]);
  }
}

function detach(cmd: string, args: string[]): void {
  const child = spawn(cmd, args, { detached: true, stdio: "ignore" });
  child.unref();
}

function warpctrl(args: string[]): string {
  const bin = getWarpctrlBin();
  if (!bin) throw new Error("warpctrl is not available");
  return execFileSync(bin, args, { encoding: "utf8", timeout: 5000 });
}

// ---------------------------------------------------------------------------
// Pane I/O
// ---------------------------------------------------------------------------

export function readSpec(id: string): WarpSurfaceSpec {
  const p = join(surfaceDir(id), SURFACE_FILES.spec);
  if (!existsSync(p)) throw new Error(`Unknown Warp surface: ${id}`);
  return JSON.parse(readFileSync(p, "utf8")) as WarpSurfaceSpec;
}

export function readStatus(id: string): WarpSurfaceStatus | null {
  const p = join(surfaceDir(id), SURFACE_FILES.status);
  let status: WarpSurfaceStatus;
  try {
    status = JSON.parse(readFileSync(p, "utf8")) as WarpSurfaceStatus;
  } catch {
    return null;
  }

  // Warp gives us no pane-death event (a user can just close the tab), and a
  // hard-killed bootstrap never runs its EXIT trap. Reconcile against the OS so
  // supervision never waits on a surface that is already gone.
  if (status.state === "running" && status.pid && !isPidAlive(status.pid)) {
    const reconciled: WarpSurfaceStatus = {
      ...status,
      state: "exited",
      exitCode: status.exitCode ?? null ?? undefined,
      stale: true,
      updatedAt: Date.now(),
    };
    try {
      writeStatus(id, reconciled);
      // Keep the sentinel contract intact for pollForExit's screen-scrape path.
      const log = join(surfaceDir(id), SURFACE_FILES.log);
      if (existsSync(log) && !readFileSync(log, "utf8").includes("__SUBAGENT_DONE_")) {
        appendFileSync(log, "\n__SUBAGENT_DONE_1__\n");
      }
    } catch {
      /* best effort */
    }
    return reconciled;
  }
  return status;
}

export function isPidAlive(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch (err) {
    // EPERM means the process exists but belongs to someone else.
    return (err as NodeJS.ErrnoException).code === "EPERM";
  }
}

function writeStatus(id: string, status: WarpSurfaceStatus): void {
  // Atomic: the bootstrap writes this file too (on start, on resize, on exit)
  // and warpCloseSurface() reconciles concurrently. A plain overwrite lets a
  // reader observe a half-written file, which readStatus() would silently treat
  // as "no status" and drop the surface from supervision.
  const target = join(surfaceDir(id), SURFACE_FILES.status);
  const tmp = `${target}.${process.pid}.tmp`;
  writeFileSync(tmp, JSON.stringify(status, null, 2));
  renameSync(tmp, target);
}

/**
 * Queue text for the pane. The bootstrap feeds `in.fifo` straight into the
 * child's stdin, so this reaches a running TUI exactly like `send-keys -l`.
 */
export function warpSendText(id: string, text: string): void {
  const spec = readSpec(id);
  const status = readStatus(id);
  if (status?.state === "exited") {
    throw new Error(
      `Warp surface ${id} has exited (code ${status.exitCode ?? "unknown"}); nothing to send to.`,
    );
  }
  // Distinguish "tab has not opened yet" from "pane died". The FIFO only exists
  // once the bootstrap runs, so a send issued straight after createWarpSurface()
  // must read as retryable, not as a dead pane. A surface that never reaches
  // "running" (hook missing, tab never opened) would otherwise report "retry
  // shortly" forever, so it becomes a hard error once the budget elapses.
  if (status?.state === "starting" && !existsSync(spec.input)) {
    const age = Date.now() - (status.updatedAt ?? spec.createdAt);
    if (age > startTimeoutMs()) {
      throw new Error(
        `Warp surface ${id} never bootstrapped after ${Math.round(age / 1000)}s. ` +
          `The tab may have failed to open, or the pane hook is not installed — ${warpSetupHint()}`,
      );
    }
    throw new Error(
      `Warp surface ${id} is still starting (the tab has not bootstrapped yet); retry shortly.`,
    );
  }
  if (process.platform === "win32") {
    // No FIFOs: append to a spool file the PowerShell bootstrap drains.
    appendSpool(spec.input, text);
    return;
  }
  // Writing to a FIFO blocks until a reader attaches; the bootstrap keeps one
  // open for the pane's lifetime, and we cap the wait so a dead pane can't hang pi.
  writeFifo(spec.input, text);
}

/**
 * Submit a line to the pane.
 *
 * Terminates with CR (0x0D) — what a physical Enter key sends — not LF.
 * A pty in canonical mode maps CR→NL (ICRNL) so shells behave identically,
 * but raw-mode TUIs (pi, claude, codex …) only accept CR, and silently keep
 * the text sitting unsubmitted in their input box otherwise.
 * Override with PI_WARP_SUBMIT_KEY=cr|lf|crlf if a pane needs something else.
 */
export function warpSendCommand(id: string, command: string): void {
  warpSendText(id, command + submitKey());
}

export function submitKey(): string {
  switch (process.env.PI_WARP_SUBMIT_KEY?.trim().toLowerCase()) {
    case "lf":
      return "\n";
    case "crlf":
      return "\r\n";
    default:
      return "\r";
  }
}

export function warpSendEscape(id: string): void {
  warpSendText(id, "\x1b");
}

function appendSpool(path: string, text: string): void {
  // Each record is one length-prefixed line so partial reads can't split escapes.
  const payload = `${Buffer.byteLength(text, "utf8")}:${Buffer.from(text, "utf8").toString("base64")}\n`;
  mkdirSync(dirname(path), { recursive: true });
  appendFileSync(path, payload);
}

function writeFifo(path: string, text: string): void {
  if (!existsSync(path)) {
    throw new Error(
      `Warp surface input channel is gone (${path}). The pane closed or the bootstrap exited.`,
    );
  }
  // The bootstrap holds the FIFO open for the pane's lifetime, so this returns
  // immediately; the timeout stops a dead pane from ever hanging the parent.
  execFileSync("/bin/sh", ["-c", `printf %s "$0" > "$1"`, text, path], {
    encoding: "utf8",
    timeout: 3000,
  });
}

import { renderTail } from "./warp-screen.ts";

const ANSI = /[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g;
/** OSC sequences (window titles, hyperlinks) terminated by BEL or ST. */
const OSC = /\u001b\][^\u0007\u001b]*(?:\u0007|\u001b\\)/g;

export function stripAnsi(s: string): string {
  return s.replace(OSC, "").replace(ANSI, "").replace(/\r(?!\n)/g, "\n");
}

/** Bytes of transcript replayed per read. Bounded so a long-lived chatty TUI
 *  cannot make every poll O(total session output). */
function logTailBytes(): number {
  const raw = Number(process.env.PI_WARP_LOG_TAIL_BYTES);
  return Number.isFinite(raw) && raw > 0 ? raw : 2 * 1024 * 1024;
}

/**
 * How much transcript a given request actually needs.
 *
 * `pollForExit` asks for 5 lines every second; replaying the full 2 MB cap for
 * that costs ~277ms per poll on a large log. A TUI repaints whole frames, so we
 * still need comfortably more than the requested rows — hence a generous
 * per-cell multiplier and a 256 KB floor — but not megabytes.
 */
function tailBytesFor(lines: number, cols: number): number {
  const cap = logTailBytes();
  const needed = Math.max(1, lines) * Math.max(40, cols) * 64;
  return Math.max(256 * 1024, Math.min(cap, needed));
}

/** How long a surface may sit in "starting" before we call it a failure. */
function startTimeoutMs(): number {
  const raw = Number(process.env.PI_WARP_START_TIMEOUT_MS);
  return Number.isFinite(raw) && raw > 0 ? raw : 60_000;
}

/**
 * Trim a byte slice to whole UTF-8 characters.
 *
 * `readTail` cuts on a byte offset, so the first bytes can be the tail of a
 * multi-byte character and the last bytes can be an incomplete one (the pty is
 * still being written to). Decoding either produces U+FFFD, which then flows
 * straight into the renderer as visible corruption.
 */
export function alignUtf8(buf: Buffer): Buffer {
  let start = 0;
  // Drop orphaned continuation bytes (10xxxxxx) at the head.
  while (start < buf.length && (buf[start] & 0xc0) === 0x80) start++;

  // Drop a trailing sequence that is not complete yet.
  let end = buf.length;
  for (let back = 1; back <= 4 && end - back >= start; back++) {
    const b = buf[end - back];
    if ((b & 0xc0) === 0x80) continue; // still inside the sequence
    const needed = b < 0x80 ? 1 : b >= 0xf0 ? 4 : b >= 0xe0 ? 3 : b >= 0xc0 ? 2 : 1;
    if (needed > back) end -= back; // incomplete — cut it off
    break;
  }
  return buf.subarray(start, end);
}

/** Read at most the last `logTailBytes()` of a file, without loading the rest. */
function readTail(path: string, maxBytes: number): string {
  let fd: number | undefined;
  try {
    fd = openSync(path, "r");
    const size = fstatSync(fd).size;
    const start = Math.max(0, size - maxBytes);
    const length = size - start;
    if (length <= 0) return "";
    const buf = Buffer.allocUnsafe(length);
    readSync(fd, buf, 0, length, start);
    // Only the head needs realigning when we actually cut; a full read starts
    // at byte 0 and is already aligned.
    return (start > 0 ? alignUtf8(buf) : buf).toString("utf8");
  } catch {
    return "";
  } finally {
    if (fd !== undefined) {
      try {
        closeSync(fd);
      } catch {
        /* ignore */
      }
    }
  }
}

/**
 * Tail of the pane as it would actually appear on screen.
 *
 * The transcript is a pty byte stream, not a grid: a TUI repaints by moving the
 * cursor, so naive line-slicing returns startup banners forever. We therefore
 * replay the stream through a small VT emulator (warp-screen.ts) using the
 * pane's recorded geometry. Set PI_WARP_SCREEN=raw to get the stripped
 * transcript instead (useful when debugging the bootstrap itself).
 */
export function warpReadScreen(id: string, lines = 50): string {
  const spec = readSpec(id);
  if (!existsSync(spec.log)) return "";
  const status = readStatus(id);
  const rows = status?.rows ?? 24;
  const cols = status?.cols ?? 80;
  const raw = readTail(spec.log, tailBytesFor(Math.max(lines, rows), cols));
  if (!raw) return "";

  if (process.env.PI_WARP_SCREEN === "raw") {
    const cleaned = stripAnsi(raw).split("\n");
    return cleaned.slice(-Math.max(1, lines)).join("\n");
  }

  return renderTail(raw, lines, { rows, cols });
}

export async function warpReadScreenAsync(id: string, lines = 50): Promise<string> {
  return warpReadScreen(id, lines);
}

/** Rename the Warp pane/tab when local control is available. */
export function warpRename(id: string, title: string): void {
  if (!isWarpctrlAvailable()) return;
  const status = readStatus(id);
  const target = status?.paneId ? ["--pane", status.paneId] : [];
  try {
    warpctrl(["pane", "rename", ...target, title]);
  } catch {
    /* cosmetic */
  }
}

export function warpRenameTab(title: string): void {
  if (!isWarpctrlAvailable()) return;
  try {
    warpctrl(["tab", "rename", title]);
  } catch {
    /* cosmetic */
  }
}

/**
 * Close a surface. Preference order:
 *   1. `warpctrl pane close` on the mapped pane (real Warp close semantics),
 *   2. kill the bootstrap process group (the shell exits → Warp closes the tab),
 *   3. drop the marker so a future shell in that dir does not re-bootstrap.
 */
export function warpCloseSurface(id: string): void {
  const status = readStatus(id);
  if (status?.paneId && isWarpctrlAvailable()) {
    try {
      warpctrl(["pane", "close", "--pane", status.paneId]);
    } catch {
      /* fall through */
    }
  }

  // Kill the bootstrap's process group, then any child it reported. Warp closes
  // the tab once its shell is gone; the group kill also reaps orphaned TUIs
  // (e.g. a `pi` that outlived a hard-killed bootstrap).
  for (const pid of [status?.pid, status?.childPid]) {
    if (!pid || !isPidAlive(pid)) continue;
    for (const target of process.platform === "win32" ? [pid] : [-pid, pid]) {
      try {
        process.kill(target, "SIGHUP");
      } catch {
        /* already gone or not a group leader */
      }
    }
    try {
      if (isPidAlive(pid)) process.kill(process.platform === "win32" ? pid : -pid, "SIGTERM");
    } catch {
      /* best effort */
    }
  }

  try {
    rmSync(join(surfaceDir(id), SURFACE_FILES.marker), { force: true });
  } catch {
    /* best effort */
  }
  // Reconcile immediately so callers do not observe a zombie "running".
  readStatus(id);
}

/** Remove a surface directory once the parent has consumed its transcript. */
export function warpDisposeSurface(id: string): void {
  rmSync(surfaceDir(id), { recursive: true, force: true });
}

/** Surfaces still on disk — used by supervision/orphan reconciliation. */
export function listWarpSurfaces(): WarpSurfaceStatus[] {
  const root = surfacesRoot();
  if (!existsSync(root)) return [];
  const out: WarpSurfaceStatus[] = [];
  for (const entry of readdirSync(root)) {
    const status = readStatus(entry);
    if (status) out.push(status);
  }
  return out;
}

// ---------------------------------------------------------------------------
// Manual fallback: Warp tab configs
// ---------------------------------------------------------------------------

/**
 * Warp tab configs (`~/.warp/tab_configs/*.toml`) can run commands on open, but
 * Warp exposes no URI to open one programmatically. We still emit one per
 * surface so a user whose hook is missing (or whose Warp build blocks
 * `warp://action/new_tab`) can start the pane from the `+` menu by hand.
 */
export function writeTabConfig(id: string): string {
  const spec = readSpec(id);
  const dir = join(warpDataDir(), "tab_configs");
  mkdirSync(dir, { recursive: true });
  const file = join(dir, `pi_subagent_${id}.toml`);
  const bootstrap = bootstrapScriptPath();
  const cmd =
    process.platform === "win32"
      ? `& '${bootstrap}' -SurfaceDir '${surfaceDir(id)}'`
      : `bash '${bootstrap}' '${surfaceDir(id)}'`;
  const toml = [
    `name = "pi subagent: ${tomlEscape(spec.name)}"`,
    `title = "${tomlEscape(spec.name)}"`,
    "",
    "[[panes]]",
    `id = "main"`,
    `type = "terminal"`,
    `directory = "${tomlEscape(surfaceDir(id))}"`,
    `commands = ["${tomlEscape(cmd)}"]`,
    `is_focused = true`,
    "",
  ].join("\n");
  writeFileSync(file, toml);
  return file;
}

export function tomlEscape(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/** Drop tab configs this package generated. */
export function cleanupTabConfigs(): void {
  const dir = join(warpDataDir(), "tab_configs");
  if (!existsSync(dir)) return;
  for (const f of readdirSync(dir)) {
    if (f.startsWith("pi_subagent_")) rmSync(join(dir, f), { force: true });
  }
}

/** Diagnostic snapshot for `/doctor`-style output. */
export function warpDiagnostics(): Record<string, unknown> {
  return {
    insideWarp: isInsideWarp(),
    warpBin: getWarpBin(),
    warpctrlBin: getWarpctrlBin(),
    warpctrlResponding: getWarpctrlBin() ? isWarpctrlAvailable() : false,
    hookInstalled: isWarpHookInstalled(),
    dataDir: warpDataDir(),
    stateDir: warpStateDir(),
    bootstrap: bootstrapScriptPath(),
    tmp: tmpdir(),
    platform: process.platform,
  };
}
